version: "3.3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: '${DOMAIN} -> http://app:${PORT}/'
      STAGE: local
      FORCE_RENEW: 'false'

  db:
    image: mysql:5.7
    container_name: dentalk-mysql
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentalk-node
    restart: always
    env_file: .env
    depends_on: 
      - db
    environment: 
      NODE_ENV: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/build
      - /usr/app/public
    working_dir: /usr/app
    command: npm run dev
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"