version: "3"

services:
  db:
    image: mysql:5.7
    container_name: dentalk-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - ${DB_PORT}:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentalk-node
    restart: always
    user: "node"
    env_file: .env
    depends_on: 
      - db
    ports:
      - 80:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/build
      - /usr/app/public
      - /usr/app/node_modules
    working_dir: /usr/app
    command: node ./build/main.bundle.js
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"