version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: dentalk-mysql
    restart: always
    volumes:
      - .docker/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  app:
    build: .
    container_name: dentalk-node
    restart: always
    env_file: .env
    environment: 
      NODE_ENV: development
    depends_on: 
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
      - build:/usr/app/build
      - public:/usr/app/public
    working_dir: /usr/app
    command: npm run dev
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"

volumes:
    node_modules:
    build:
    public: